/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectorRouteImport } from './routes/projector'
import { Route as PIndexRouteImport } from './routes/p.index'
import { Route as PTokenRouteImport } from './routes/p.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectorRoute = ProjectorRouteImport.update({
  id: '/projector',
  path: '/projector',
  getParentRoute: () => rootRouteImport,
} as any)
const PIndexRoute = PIndexRouteImport.update({
  id: '/p/',
  path: '/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projector': typeof ProjectorRoute
  '/p/$token': typeof PTokenRoute
  '/p/': typeof PIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projector': typeof ProjectorRoute
  '/p/$token': typeof PTokenRoute
  '/p': typeof PIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projector': typeof ProjectorRoute
  '/p/$token': typeof PTokenRoute
  '/p/': typeof PIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projector' | '/p/$token' | '/p/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projector' | '/p/$token' | '/p'
  id: '__root__' | '/' | '/projector' | '/p/$token' | '/p/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectorRoute: typeof ProjectorRoute
  PTokenRoute: typeof PTokenRoute
  PIndexRoute: typeof PIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projector': {
      id: '/projector'
      path: '/projector'
      fullPath: '/projector'
      preLoaderRoute: typeof ProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/': {
      id: '/p/'
      path: '/p'
      fullPath: '/p/'
      preLoaderRoute: typeof PIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectorRoute: ProjectorRoute,
  PTokenRoute: PTokenRoute,
  PIndexRoute: PIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
